### ISSUE TITLE
Percussions?

### ISSUE THREAD

**Issue by didibus** [oakes/edna#1]
It seems Alda percussions have each note map to a different percussion instrument. Its quite inconvenient to put a full {:octave x} before the note in this case. Maybe we could a short-hand syntax could be added which allows you to shift the octave precisely like `:2b` which would be the same as `{:octave 2} :b`?

**Comment by oakes** [comment]
Currently `:2b` will be parsed as `:+2b` (a relative increase in octave) so at this point it would be a breaking change to do that. Maybe it wouldn't affect anyone, though, since normally you'd have the + or - in there. I'll experiment a bit with this...

**Comment by 0atman** [comment]
the way I'd solve this in the meantime is to make named variables, which you can merge into your vector. You can be as verbose or terse as you would like. `KI HA SN HA KI`!

```clojure
(def snare [{:octave 2} :e])
```

**Comment by oakes** [comment]
Thanks that's a great idea. BTW I do intend on making the change but I'm on vacation at the moment. In about a week I'll push the change so this is easier to do.

**Comment by 0atman** [comment]
Thanks @oakes!

**Comment by oakes** [comment]
The requested change is now in edna 1.6.0! please let me know if you notice any problems.

**Comment by 0atman** [comment]
YES dude.
